export enum DocumentType {
  GOVERNMENT_ID = 'GOVERNMENT_ID',
  RIGHT_TO_WORK = 'RIGHT_TO_WORK',
  LIABILITY_INSURANCE = 'LIABILITY_INSURANCE',
  REFERENCE = 'REFERENCE',
  PROFILE_PHOTO = 'PROFILE_PHOTO',
}
